### ISSUE TITLE
无法解码

### ISSUE THREAD

**Issue by Cathgao** [toyobayashi/mishiro#2]
下载完毕后无法解码，CPU占用维持高水平，但长时间无法输出文件
![2](https://user-images.githubusercontent.com/21031564/36540576-dcd20926-1815-11e8-9fec-4de5943f35bc.PNG)

**Comment by toyobayashi** [comment]
我这里没问题。。你打开文件夹看看，有输出hca文件吗？

**Comment by toyobayashi** [comment]
命令行cd进mishiro的安装目录，在命令行敲mishiro --enable-logging启动程序，再去执行选择live曲的操作，看报什么错没有

**Comment by RainbowO3** [comment]
没有报错，没有输出hca文件

**Comment by RainbowO3** [comment]
看错文件夹了，有输出hca但是没有输出相应的mp3

**Comment by RainbowO3** [comment]
D:\Program Files (x86)\mishiro>
manifest: 43600
bgm: 208
live: 225
eventID: 1030
gachaID: 30218
(node:6140) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: D:\Program Files (x86)\mishiro\resources\app\bin\AcbUnzip.exe D:\Program Files (x86)\mishiro\resources\app\public\asset\sound\bgm\bgm_event_1030.acb
'D:\Program' 锟斤拷锟斤拷锟节诧拷锟斤拷锟解部锟斤拷锟筋，也锟斤拷锟角匡拷锟斤拷锟叫的筹拷锟斤拷
锟斤拷锟斤拷锟斤拷锟斤拷锟侥硷拷锟斤拷

(node:6140) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[6140:0224/004437.667:INFO:CONSOLE(0)] "Uncaught (in promise) NotSupportedError: Failed to load because no supported source was found.", source: file:///D:/Program%20Files%20(x86)/mishiro/resources/app/public/index.html (0)
(node:6140) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Command failed: D:\Program Files (x86)\mishiro\resources\app\bin\AcbUnzip.exe D:\Program Files (x86)\mishiro\resources\app\public\asset\sound\live\song_3024.acb
'D:\Program' 锟斤拷锟斤拷锟节诧拷锟斤拷锟解部锟斤拷锟筋，也锟斤拷锟角匡拷锟斤拷锟叫的筹拷锟斤拷
锟斤拷锟斤拷锟斤拷锟斤拷锟侥硷拷锟斤拷

[6140:0224/004522.087:INFO:CONSOLE(1)] "abort: http://storage.game.starlight-stage.jp/dl/resources/High/Sound/Common/l/4f3bc20ed75be983a8e0f6a1e37d1cb4", source: file:///D:/Program%20Files%20(x86)/mishiro/resources/app/public/mishiro.min.js (1)
(node:6140) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Command failed: D:\Program Files (x86)\mishiro\resources\app\bin\AcbUnzip.exe D:\Program Files (x86)\mishiro\resources\app\public\asset\sound\live\song_1041.acb
'D:\Program' 锟斤拷锟斤拷锟节诧拷锟斤拷锟解部锟斤拷锟筋，也锟斤拷锟角匡拷锟斤拷锟叫的筹拷锟斤拷
锟斤拷锟斤拷锟斤拷锟斤拷锟侥硷拷锟斤拷

原来是在cmd看报错，我错了（。）

**Comment by toyobayashi** [comment]
我大概知道了，你把整个应用换个安装位置试试，不要放在路径有空格的地方，Program Files有空格。

**Comment by toyobayashi** [comment]
感谢反馈，问题已确认。下个版本将会修复

**Comment by Cathgao** [comment]
换了无空格目录之后问题解决了。但是无ui的CGSSAssetsDownloader就算在根目录也无法解析mainfest，也请关注一下。很喜欢你的下载器
